Add recaptcha to user creation form
rsinghal/giza pull request #160
Opened 2021-04-15 15:29 UTC by lukehollis

Closes #155

2021-04-20 19:04 UTC, rsinghal requested changes

2021-04-20 19:04 UTC, rsinghal commented on requirements.txt
> +Django==2.2.12
Please fix the Django versioning to use the latest version of 2.2, not restrict it to a single version.

2021-04-21 13:17 UTC, lukehollis commented
Confirmed updated the `requirements.txt`.

2021-04-22 13:22 UTC, rsinghal approved these changes

2021-06-03 14:16 UTC, rsinghal commented
@lukehollis this is currently on giza-web2, but the captcha isn't showing up.  I don't see any errors in the console, so can you take a look and see if there is anything obvious?  Or let me know if there is anything I should be checking?

2026-03-11 10:39 UTC, closed without merging