Advanced search layout
rsinghal/giza pull request #173
Opened 2021-10-15 21:21 UTC by muildrik

2021-10-25 18:26 UTC, rsinghal requested changes

2021-11-03 21:39 UTC, muildrik reviewed
Added a few files and moving on to MET--will have a branch ready for that soon. What works best for you guys to surface new fields? Also, advanced search by date range requires a field entrydate_ms; I've written a script to convert dates in entrydate fields to milliseconds for that function to work. Would you want to run that locally or do you have another way?

2021-11-05 17:59 UTC, muildrik commented on offline_scripts/elasticsearch_iiif_delete_index.sh
> +curl -sv -XDELETE "http://localhost:9200/iiif" | less
curl needs to be verbose and silent on my local dev

2021-11-05 18:05 UTC, muildrik commented on offline_scripts/elasticsearch_setup.sh
> +curl -sv -XPUT 'http://localhost:9200/giza' -d '
verbose and silent is required for my local dev

2021-11-05 18:20 UTC, rsinghal commented on offline_scripts/elasticsearch_setup.sh
> +curl -sv -XPUT 'http://localhost:9200/giza' -d '
I understand you need it for your local dev, but you shouldn't be submitting that to the master as it's not what we use on the prod and dev servers.  You can keep that as a local change.  Please fix.

2021-11-05 18:23 UTC, rsinghal reviewed
Please add a list of all changes and new features to the description of this PR.  Due to the sheer number of changes in this PR, we may need to set up a time to do a code review.

2021-11-05 20:09 UTC, muildrik reviewed
- Removed flags and added other files to .gitignore. 
- views_utils.py has MET dictionary and is therefore stupidly long; 
- search.html has new HTML markup for advanced search, nothing special there. 
- rewritten a few functions in giza.js, but functionality exactly the same (basically only changed a few function calls to modern standards)
- search_tags.py: two functions that are part of MET and don't do anything yet--may well disappear in future commits
- views.py: rewritten functions, added functions to convert entrydate text string to milliseconds for querying; added small subroutine for querying ES to look for milliseconds if request is entrydate field

2021-11-05 20:09 UTC, muildrik commented on offline_scripts/elasticsearch_delete_index.sh
> +curl -sv -XDELETE "http://localhost:9200/giza" | less
Added to .gitignore

2026-07-13 16:06 UTC, closed without merging